# Use the official PostgreSQL image as a base
FROM postgres

# RUN apt-get update && apt install iputils-ping -y

# Set environment variables
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=db

# Expose the PostgreSQL port
EXPOSE 5432
