version: '3'
services:
  client:
    build:
      context: ./client
    ports:               # left port: local machine port, right port: docker container port
      - "8081:8081"
      # - "8087:8081"    # localhost:8087 -> client docker container port 8081

  server:
    build:
      context: ./server/server
    ports:
      - "8080:8080"
      # - "8086:8080"

  ui:
    build:
      context: ./server/ui
    ports:
      - "8082:3000"