version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "8081:8081"
    # Add other client-specific configurations

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    # Add other server-specific configurations
