version: '3'
services:

  # db: 
  #   image: postgres
  #   container_name: db
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: db 
  #   volumes:
  #     - ./server/db/clear-db-data.sh:/clear-db-data.sh
  #     - ./server/db-data:/var/lib/postgresql/data
  #     - ./server/db/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
  #   entrypoint: ["/bin/sh", "/clear-db-data.sh"]
  #   ports:
  #     - '5432:5432'
  db: 
    image: postgres
    container_name: db
    build:
      context: ./server/db 
    restart: always
    volumes:
      - ./server/db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

  client:
    image: client
    container_name: client
    restart: always
    build:
      context: ./client
    ports:               
      - "8081:8081"
    volumes:
      - ./client/config.json:/app/config.json

  network:
    image: network
    container_name: network
    restart: always
    build:
      context: ./server/network
    ports:
      - "8080:8080"
    depends_on:
      - db

  ui:
    image: ui
    container_name: ui
    restart: always
    build:
      context: ./server/ui
    ports:
      - "8082:3000"
    depends_on:
      - db


