version: '3'
services:

  db: 
    image: postgres
    container_name: db
    build:
      context: ./server/db 
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    # volumes:
    #   - ./server/db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  client:
    image: client
    container_name: client
    restart: always
    build:
      context: ./client
    ports:               
      - "8081:8081"
    volumes:
      - ./client/config.json:/app/config.json

  network:
    image: network
    container_name: network
    restart: always
    build:
      context: ./server/network
    ports:
      - "8080:8080"
    depends_on:
      - db

  ui:
    image: ui
    container_name: ui
    restart: always
    build:
      context: ./server/ui
    ports:
      - "8082:3000"
    depends_on:
      - db


volumes:
  db-data: