version: '3'
services:
  webcam_capture:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: webcam_capture_container
    restart: always
    ports:
      - "8080:8080"

  coco_object_detection:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: information_extraction_container
    restart: always
    ports:
      - "8000:8000"
