version: '3'
services:

  db: # command to view postgresql cli: docker exec -it <db_container_id> psql -U postgres db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db 
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./server/db/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
    ports:
      - '5432:5432'

  client:
    build:
      context: ./client
    ports:               # left port: local machine port, right port: docker container port
      - "8081:8081"
      # - "8087:8081"    # localhost:8087 -> client docker container port 8081

  server:
    build:
      context: ./server/server
    ports:
      - "8080:8080"
      # - "8086:8080"
    depends_on:
      - db

  ui:
    build:
      context: ./server/ui
    ports:
      - "8082:3000"
    depends_on:
      - db


